version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.12.2
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      cluster.routing.allocation.disk.watermark.enable_for_single_data_node: true
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
    networks:
      - elastic
    volumes:
      - data01:/usr/share/elasticsearch/data
    healthcheck:
      interval: 10s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/
  kibana:
    image: kibana:8.12.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
volumes:
  data01:
    driver: local
